[tasks.build-backend]
cwd = "./back_end/"
command = "cargo"
args = ["build", "--release"]

[tasks.npm-install]
cwd = "./front_end/"
command = "npm"
args = ["install"]

[tasks.build-web]
cwd = "./front_end/"
command = "npm"
args = ["run", "build"]
dependencies = ["npm-install"]

[tasks.build]
clear = true
dependencies = ["build-backend", "build-web"]

[tasks.release]
command = "tar"
args = [
    "caf",
    "release.tar.xz",
    "-C",
    "./back_end/target/release/",
    "toukakoukan",
    "-C",
    "../../../front_end",
    "./dist/",
]
dependencies = ["build"]
