[package]
name = "svelte-axum-project"
version = "0.4.2"
edition = "2021"
repository = "https://github.com/jbertovic/svelte-axum-project"
keywords = ["template", "backend", "frontend", "axum", "svelte"]
license = ""
categories = []
description = ""


[dependencies]
axum = { version = "0.7.2", features = ["macros"] }
tower = "0.4.13"
tower-http = { version = "0.5", features = ["full"] }
tower-sessions = { version = "0.8.2", features = ["sqlite-store"] }
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7.3", features = ["sqlite", "time", "runtime-tokio", "migrate"] }
password-auth = "1.0.0"
time = "0.3.31"
axum-macros = "0.4.0"
anyhow = "1.0.77"
