name: CI
on: [push, pull_request]
jobs:
  build_rust:
    name: "Rust Project"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          workspace: back_end
      - run: cargo build
        working-directory: back_end
  build_web:
    name: "Build web"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
        working-directory: front_end
      - run: npm run build
        working-directory: front_end
